# Generated by Django 5.1.7 on 2025-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='piece',
            field=models.IntegerField(default=1),
        ),
    ]
