# Generated by Django 5.1.7 on 2025-07-02 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_deliveryorder_status_alter_deliveryorder_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='app.deliveryboy'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
