# Generated by Django 5.1.7 on 2025-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_deliveryorder_order_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
