# Generated by Django 5.1.7 on 2025-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
    ]
