# Generated by Django 5.1.7 on 2025-07-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_returnrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
