# Generated by Django 5.1.7 on 2025-07-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_returnrequest_collected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
