# Generated by Django 5.1.7 on 2025-07-03 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be numeric and up to 11 digits.', regex='^\\d{1,11}$')]),
        ),
    ]
