# Generated by Django 5.1.7 on 2025-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_deliveryboy_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('t-shirt', 'T-shirt'), ('saree', 'Saree'), ('shoes', 'Shoes'), ('jeans', 'Jeans'), ('fans', 'Fans'), ('toys', 'Toys'), ('cake', 'Cake'), ('dryfruits', 'Dryfruits'), ('ear-phone', 'Ear-phone'), ('laptop', 'Laptop'), ('car', 'Car'), ('frame', 'Frame')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(default='pics/nature.jpg', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
