# Generated by Django 5.1.7 on 2025-07-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_blogs_category_alter_blogs_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='confirmed_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='marked_delivered_by_boy',
            field=models.BooleanField(default=False),
        ),
    ]
