# Generated by Django 5.1.7 on 2025-07-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_deliveryorder_confirmed_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_info', to='app.order'),
        ),
    ]
