# Generated by Django 5.1.7 on 2025-07-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_deliveryorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_product', to='app.product')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_product', to='app.product')),
            ],
        ),
    ]
