# Generated by Django 5.1.7 on 2026-04-11 10:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='authname',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('t-shirt', 'T-shirt'), ('saree', 'Saree'), ('shoes', 'Shoes'), ('jeans', 'Jeans'), ('fans', 'Fans'), ('toys', 'Toys'), ('cake', 'Cake'), ('dryfruits', 'Dryfruits'), ('ear-phone', 'Ear-phone'), ('laptop', 'Laptop'), ('car', 'Car'), ('frame', 'Frame')], db_index=True, default='shirt', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, default='Uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('salesman', 'Salesman'), ('customer', 'Customer')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be numeric and up to 11 digits.', regex='^\\d{1,11}$')]),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['category', 'timeStamp'], name='app_blogs_categor_62771c_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'product'], name='app_cartite_user_id_c339dc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'created_at'], name='app_comment_product_aa9b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['status', 'created_at'], name='app_deliver_status_a58ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['assigned_to', 'status'], name='app_deliver_assigne_af6a10_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='app_message_sender__a104cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='app_message_sender__324d69_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'timestamp'], name='app_message_receive_096e74_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='app_order_user_id_7682e1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'delivery_status'], name='app_order_user_id_aaaef0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_status', 'created_at'], name='app_order_deliver_c4c465_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sale_price'], name='app_product_categor_d3144e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'stock'], name='app_product_categor_b7d76f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'timestamp'], name='app_recomme_user_id_f4e959_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['product', 'timestamp'], name='app_recomme_product_8d2ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', 'status'], name='app_returnr_custome_87a63c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', 'created_at'], name='app_returnr_status_9ea01e_idx'),
        ),
    ]
