# Generated by Django 5.1.7 on 2026-06-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_product_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='app.product'),
        ),
    ]
