# Generated by Django 5.1.7 on 2026-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reason',
            field=models.TextField(default='NO reason provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='returns/videos/'),
        ),
    ]
