# Generated by Django 5.1.7 on 2026-06-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_returnrequest_image_returnrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='app.order'),
        ),
    ]
