# Generated by Django 5.1.7 on 2026-06-21 08:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_returnrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='returns/videos/'),
        ),
    ]
