# Generated by Django 5.1.7 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_returnrequest_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('t-shirt', 'T-shirt'), ('saree', 'Saree'), ('shoes', 'Shoes'), ('jeans', 'Jeans'), ('fans', 'Fans'), ('toys', 'Toys'), ('cake', 'Cake'), ('dryfruits', 'Dryfruits'), ('ear-phone', 'Ear-phone'), ('laptop', 'Laptop'), ('car', 'Car'), ('frame', 'Frame')], db_index=True, default='shirt', max_length=100),
        ),
    ]
