# Generated by Django 5.1.7 on 2026-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.CharField(blank=True, help_text='Example: S,M,L,XL or 1 pound,1.5 pound', max_length=500, null=True),
        ),
    ]
