# Generated by Django 5.1.7 on 2026-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_blogs_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('shirt', 'শার্ট'), ('t-shirt', 'টি-শার্ট'), ('saree', 'শাড়ি'), ('shoes', 'জুতা'), ('jeans', 'জিন্স'), ('fans', 'ফ্যান'), ('toys', 'খেলনা'), ('cake', 'কেক'), ('dryfruits', 'শুকনো ফল'), ('ear-phone', 'ইয়ারফোন'), ('laptop', 'ল্যাপটপ'), ('car', 'গাড়ি'), ('frame', 'ফ্রেম'), ('ornament', 'গহনা')], db_index=True, default='shirt', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'শার্ট'), ('t-shirt', 'টি-শার্ট'), ('saree', 'শাড়ি'), ('shoes', 'জুতা'), ('jeans', 'জিন্স'), ('fans', 'ফ্যান'), ('toys', 'খেলনা'), ('cake', 'কেক'), ('dryfruits', 'শুকনো ফল'), ('ear-phone', 'ইয়ারফোন'), ('laptop', 'ল্যাপটপ'), ('car', 'গাড়ি'), ('frame', 'ফ্রেম'), ('ornament', 'গহনা')], db_index=True, default='shirt', max_length=100),
        ),
    ]
